[package]
name = "hmeasure"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
rand = "0.8.5"
rand_distr = "0.4.3"
statrs = "0.16.0"
